### ISSUE TITLE
Php extension (php7-tokenizer) missing

### ISSUE THREAD

**Issue by QuentinPetel** [upshift-docker/dolibarr#1]
php7-tokenizer extension is missing when we want to use the dolibarr API REST module with your image. We get the following error on {{DOLIBARR_URL}}/api/index.php/explorer/ :
```
Call to undefined function Luracast\\Restler\\token_get_all()
```

=> Solution : install php7-tokenizer via apk in the Dockerfile

```
apk add php7-tokenizer
```

**Comment by upshift-docker** [comment]
fixed, thanks
