### ISSUE TITLE
cdav integration (caldav,carddav)

### ISSUE THREAD

**Issue by delightfuldude** [upshift-docker/dolibarr#22]
Would it be possible to integrate this into the docker file?
-> https://github.com/Befox/cdav

**Comment by laurpaum** [comment]
Hi,

Custom Dolibarr modules can be added through the web UI.

Once logged in with an admin account, go to Setup > Modules > Deploy/install external module, and upload a zip file containing the module.

Dolibarr is a bit picky about zip file and content naming. If you download release package from the cdav repository, you will need to extract the zip content, rename the "cdav-2.10" folder to "cdav", then zip the folder, naming the zip file "module_cdav-2.10.zip".

Custom modules are installed in the /var/www/html/custom folder inside the container. You will need to mount this folder from a docker volume or bind mount if you don't want to reinstall modules after every restart.

The upshift/dolibarr images were missing a required PHP dependency. You will need to pull newest images with tags 13.0, 14.0 or 15.0 for the module to work properly.

**Comment by delightfuldude** [comment]
Thank you very much! This works!!!
