### ISSUE TITLE
conf file improvement

### ISSUE THREAD

**Issue by damedp** [upshift-docker/dolibarr#25]
<?php
// Config file for Dolibarr 15.0.3 (Mon Aug  1 21:52:19 UTC 2022)

// a helper function to lookup "env_FILE", "env", then fallback
if (!function_exists('getenv_docker')) {
	function getenv_docker($env, $default) {
		if ($fileEnv = getenv($env . '_FILE')) {
			return rtrim(file_get_contents($fileEnv), "\r\n");
		}
		else if (($val = getenv($env)) !== false) {
			return $val;
		}
		else {
			return $default;
		}
	}
}

// ###################
// # Main parameters #
// ###################
$dolibarr_main_url_root=getenv_docker('DOLI_URL_ROOT', 'http://localhost');
$dolibarr_main_document_root='/var/www/html';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/var/www/html/custom';
$dolibarr_main_data_root='/var/www/documents';
$dolibarr_main_db_host=getenv_docker('DOLI_DB_HOST', 'localhost');
$dolibarr_main_db_port=getenv_docker('DOLI_DB_PORT', '3306');
$dolibarr_main_db_name=getenv_docker('DOLI_DB_NAME', 'dolibarr');
$dolibarr_main_db_prefix=getenv_docker('DOLI_DB_PREFIX', 'llx_');
$dolibarr_main_db_user=getenv_docker('DOLI_DB_USER', 'dolibarr');
$dolibarr_main_db_pass=getenv_docker('DOLI_DB_PASSWORD', '');
$dolibarr_main_db_type=getenv_docker('DOLI_DB_TYPE', 'mysqli');
$dolibarr_main_db_character_set=getenv_docker('DOLI_DB_CHARACTER_SET', 'utf8');
$dolibarr_main_db_collation=getenv_docker('DOLI_DB_COLLATION', 'utf8_unicode_ci');

// ##################
// # Login          #
// ##################
$dolibarr_main_authentication=getenv_docker('DOLI_AUTH', 'dolibarr');
$dolibarr_main_auth_ldap_host=getenv_docker('DOLI_LDAP_HOST', '127.0.0.1');
$dolibarr_main_auth_ldap_port=getenv_docker('DOLI_LDAP_PORT', '389');
$dolibarr_main_auth_ldap_version=getenv_docker('DOLI_LDAP_VERSION', '3');
$dolibarr_main_auth_ldap_servertype=getenv_docker('DOLI_LDAP_SERVERTYPE', 'openldap');
$dolibarr_main_auth_ldap_login_attribute=getenv_docker('DOLI_LDAP_LOGIN_ATTRIBUTE', 'uid');
$dolibarr_main_auth_ldap_dn=getenv_docker('DOLI_LDAP_DN', '');
$dolibarr_main_auth_ldap_filter =getenv_docker('DOLI_LDAP_FILTER', '');
$dolibarr_main_auth_ldap_admin_login=getenv_docker('DOLI_LDAP_ADMIN_LOGIN', '');
$dolibarr_main_auth_ldap_admin_pass=getenv_docker('DOLI_LDAP_ADMIN_PASS', '');
$dolibarr_main_auth_ldap_debug=getenv_docker('DOLI_LDAP_DEBUG', 'false');

// ##################
// # Security       #
// ##################
$dolibarr_main_prod=getenv_docker('DOLI_PROD', '0');
$dolibarr_main_force_https=getenv_docker('DOLI_HTTPS', '0');
$dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
$dolibarr_nocsrfcheck=getenv_docker('DOLI_NO_CSRF_CHECK', '0');
$dolibarr_main_cookie_cryptkey='0cae9b4dfe64313dd7d299c21983b57899d3e1ac88c2dabab065b8308675bcf6';
$dolibarr_mailing_limit_sendbyweb='0';

**Comment by laurpaum** [comment]
No description provided

**Comment by laurpaum** [comment]
empty issue
