### ISSUE TITLE
Php extension (php7-simplexml) missing

### ISSUE THREAD

**Issue by QuentinPetel** [upshift-docker/dolibarr#3]
php7-simplexml extension is missing when we want to use the dolibarr update fonctionnality with your image. We get the following error on {{DOLIBARR_URL}}/admin/tools/update.php?action=getlastversion :
```
Call to undefined function: simplexml_load_string()
```

=> Solution : install php7-simplexml via apk in the Dockerfile
```
apk add php7-simplexml
```

**Comment by upshift-docker** [comment]
fixed
