### ISSUE TITLE
CRON

### ISSUE THREAD

**Issue by fred-gb** [upshift-docker/dolibarr#31]
Hi,
Thanks for this docker image.
Is it possible to have a cron functionnality with this docker?
Thanks

**Comment by Vircos01** [comment]
It is a module within Dolibarr which you have to enable if I am right.

**Comment by fred-gb** [comment]
Hi,
Thanks, but something else to do I think. As you can see in documentation:
https://wiki.dolibarr.org/index.php/Module_Scheduled_jobs

```
External activation of the module

The module need to be externally activated each 5 minutes.

Depending on the environment where Dolibarr is running, the procedure to be followed is different.  
```

So in this image, I don't think there is crontab. 
And, we need this file: `wwww\dolibarr\scripts\cron\cron_run_jobs.php` . I don't find it in generates files of this docker.

Do we need to create another docker image to make call every 5 minutes?

**Comment by fred-gb** [comment]
Finally, I use an external service to send curl request every 5 minutes.
