### ISSUE TITLE
cannot complete fresh install - db connection wrong

### ISSUE THREAD

**Issue by praet0ri4n** [upshift-docker/dolibarr#4]
Hi, I just tried to setup this image wtih docker-compose, used the exact contents of the docker-compose.yml and got stuck on the step, where I shall navigate to the .../install webpage.
I choose fresh install, then there in the form I see prefilled fields that are not editable (they come from forced.install.php..) and hittng "Next step ->" returns an error "Connection refused"
![image](https://user-images.githubusercontent.com/7620960/71600334-c291cd00-2b4e-11ea-9d16-bddfd7f52dd6.png)
How to continue?

**Comment by praet0ri4n** [comment]
I had to manually connect to the mariadb docker container, create the dolibarr database and the dolibarr user. So just for info.. is there a issue maybe with the "fresh install" and your startup script? In my case the database creation step was failing...

**Comment by upshift-docker** [comment]
Empty passwords don't seem to work anymore with mariadb docker images. I updated example compose file with a password for the dolibarr user and random password for root. I also improved startup script to call dolibarr install scripts automatically. No need to go to /install and hit next / next / next anymore...
