### ISSUE TITLE
php7-json missing

### ISSUE THREAD

**Issue by TibboddiT** [upshift-docker/dolibarr#5]
Got error 500 on https://dolibarr.doamin.com/societe/paymentmodes.php?socid={id} because json extension is not enabled:

```
Interface 'JsonSerializable' not found in /var/www/html/includes/stripe/lib/StripeObject.php on line 10
```

Adding php7-json in the Dockerfile solved the issue for me.

**Comment by upshift-docker** [comment]
Fixed in latest images
