### ISSUE TITLE
htdocs/conf/conf.php permissions

### ISSUE THREAD

**Issue by vbueb** [upshift-docker/dolibarr#8]
Hi,

When logged in as an administrator, there is a notification in the bottom of home page complaining about htdocs/conf/conf.php permissions. This file once edited, should not be writable by the web server.

![Screen Capture_select-area_20200605182117](https://user-images.githubusercontent.com/55386438/83900545-25b90880-a75a-11ea-8abd-c73f07b65175.png)

This container is almost perfect, you did a very good job.

**Comment by laurpaum** [comment]
Fixed (as well as write permissions on htdocs tree) by commit 623a693049d48a554226cb8ab4f8e34740fcb3dd

Didn't notice sooner because MAIN_REMOVE_INSTALL_WARNING is enabled by default :(

**Comment by vbueb** [comment]
Wow that was fast, great thank you very much !

**Comment by laurpaum** [comment]
You're welcome, that was an easy one :)
